### ISSUE TITLE
Swipe prev card bug

### ISSUE THREAD

**Issue by khanhicetea** [her0e1c1/tango#11]
When I swipe down (prev card), it show blank without any card (current postion is 7/7)

![photo6325751202645649353](https://user-images.githubusercontent.com/4528223/35812928-de525a52-0ac4-11e8-9ade-a6507791735d.jpg)

**Comment by khanhicetea** [comment]
The last check, bug is resolved. Thanks @her0e1c1 !!

**Comment by her0e1c1** [comment]
@khanhicetea thank you for checking the bug. I was not confident that I fixed it completely.

Btw today I will fix failure of circle CI builds
