### ISSUE TITLE
[Feature Request] QR Code scanner

### ISSUE THREAD

**Issue by khanhicetea** [her0e1c1/tango#15]
Hi @her0e1c1 ,

If you have time, please have a look on this : https://docs.expo.io/versions/latest/sdk/bar-code-scanner.html

Thank you !

**Comment by her0e1c1** [comment]
Thanks for your request!

For the feature, I want to know QR code which you want to scan?

tbh I don't know qr code so don't have a good idea for this ...

**Comment by khanhicetea** [comment]
QR Code is way to encode an URL to an Image, so I will encode my CSV links to QR Code. So next time, I just scan the image without typing or copying any link.

This is my current flow to import my CSV
- Copy CSV link on desktop
- Encode it to QR code via third-party page
- Using "Scan QR code" feature of Google Chrome in mobile
- Then copying decoded URL from Chrome to Tango input

😈  haha a bit lazy and tricky

**Comment by her0e1c1** [comment]
Ah I see! good feature!!!

I thought the QR code would have its own data (not URL) haha ...

**Comment by her0e1c1** [comment]
DONE! 03d9c01144445b2d586f12c404e04bcf5c9ace70

**Comment by khanhicetea** [comment]
Wow, so fast !!!! 👍

**Comment by her0e1c1** [comment]
hehe

**Comment by khanhicetea** [comment]
It works like a charm !!! 😎 Thank you very much !

**Comment by her0e1c1** [comment]
Ya you too :) thank you for testing!!!
