### ISSUE TITLE
[UI] Please make less words and use gesture more

### ISSUE THREAD

**Issue by her0e1c1** [her0e1c1/tango#3]
@khanhicetea I have a request.

I think it's good UI if there are less words.
(ex)
- `+ import` => `+`
- `Practice this deck` => tap the deck
- `I didn't know` => swipe right
- `I knew this` => swipe top

btw I want to swipe left when I want to go back to the previous card.

**Comment by khanhicetea** [comment]
Yeah, I agree. Simpler is better !

About swiping card direction, I have some idea : 
- my direction sort by easy gesture (easier for thumb finger) : right, top (bottom) then left.
- so swipe right should be action you do most the time (knew this or didnt know)
- swipe left to previous card is good
- I have an idea that swipe top and swipe bottom should be same action.

How do you think ?

**Comment by her0e1c1** [comment]
Thank you for your agreement!

My gesture order is right, bottom, top, left btw

hmm in my case, I often use `I didn't know`. so this is to swipe right for me, (maybe we can configure)

> I have an idea that swipe top and swipe bottom should be same action.

yea this is more simple but for me currently to swipe bottom is to go back. because the 4 gestures is precious so I think it's still ok if they are not the same action

**Comment by khanhicetea** [comment]
Ok, so we could put in setting to customize gestures (can do it later). Now we could follow your idea

**Comment by her0e1c1** [comment]
ok! there are 4 actions now: `I didn't know`, `I knew this`, `Go to the previous card` and `Go to a list of cards`, we can add more actions :)

**Comment by khanhicetea** [comment]
:+1: I will update design soon

**Comment by her0e1c1** [comment]
ya thank you! please take your time with Vietnamese coffee :)
