### ISSUE TITLE
Automated publishing app to Expo host

### ISSUE THREAD

**Issue by khanhicetea** [her0e1c1/tango#4]
Publishing master branch to expo host is good for me on testing the app. So I have 2 solutions for that : 

- Using a simple git hook "after-commit" to run "expo publish" on your machine.
- Setup an CI using free CI service, then and token or expo accounts to ENV

**Comment by her0e1c1** [comment]
Thanks for your issue!

I just want to use Circle CI so ya I'm ok if I will set my account to ENV

**Comment by khanhicetea** [comment]
Resolved by #5
