### ISSUE TITLE
Some bugs I found in app

### ISSUE THREAD

**Issue by khanhicetea** [her0e1c1/tango#9]
Hi Hiro,

1. There are some tiny bugs I found in app : 
2. After importing CSV, it should show a popup to notify imported result then clean the input
3. Swipe top the card will toggle its `mastered` status instead set it `true`
4. Swipe right doesn't set `mastered` to false
5. Could we set a height for card, so it can be a card ;)
6. Card title should align center

😄

**Comment by her0e1c1** [comment]
@khanhicetea thanks! I will fix one by one!!!

**Comment by khanhicetea** [comment]
thanks, let me know when you done, I will re-test it ! 😄

**Comment by her0e1c1** [comment]
ya I am fixing one by one ya

**Comment by her0e1c1** [comment]
ah then created another bug :)

**Comment by her0e1c1** [comment]
@khanhicetea can you check this? I think I fixed them. (5. is a bit hard to fix ya ... maybe not yet ...)

**Comment by khanhicetea** [comment]
Hi Hiro, I checked the new app version.

I has good gesture setting, I can configure easily my gesture. :) Btw, when I swipe right or left (mastered or not mastered), nothing changes in card. Could you recheck that ? :D 

So, [2] and [6] is resolved !

Thanks

**Comment by her0e1c1** [comment]
@khanhicetea thank you for testing.

Sorry but I think you need to clear redux status to clear app cache and exit app.

If you still have a bug, please let me know :)

**Comment by khanhicetea** [comment]
Hi Hiro,

I just tested it by clearing app cache then exit app. But it still be the
same.

Could you re-test with this config ?

[image: Inline image 1]

Thanks !

**Comment by khanhicetea** [comment]
Sorry, here is screenshot

![photo6323499402831964144](https://user-images.githubusercontent.com/4528223/35785806-e1f96afc-0a55-11e8-8d84-66eec6dd3948.jpg)

**Comment by her0e1c1** [comment]
thanks @khanhicetea ! it's a bug
I fixed this commit 92671efd486e34d0128afa33bd2536090595e73b

**Comment by khanhicetea** [comment]
Ok, I tested and it works fine !

So I will close this issue , thanks @her0e1c1 😄
